//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3634
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Isid.KKH.Uni.Schema {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DetailDSUni")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DetailDSUni : global::System.Data.DataSet {
        
        private KkhDetailDataTable tableKkhDetail;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DetailDSUni() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DetailDSUni(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["KkhDetail"] != null)) {
                    base.Tables.Add(new KkhDetailDataTable(ds.Tables["KkhDetail"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public KkhDetailDataTable KkhDetail {
            get {
                return this.tableKkhDetail;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            DetailDSUni cln = ((DetailDSUni)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["KkhDetail"] != null)) {
                    base.Tables.Add(new KkhDetailDataTable(ds.Tables["KkhDetail"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableKkhDetail = ((KkhDetailDataTable)(base.Tables["KkhDetail"]));
            if ((initTable == true)) {
                if ((this.tableKkhDetail != null)) {
                    this.tableKkhDetail.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DetailDSUni";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DetailDSUni.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableKkhDetail = new KkhDetailDataTable();
            base.Tables.Add(this.tableKkhDetail);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeKkhDetail() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DetailDSUni ds = new DetailDSUni();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void KkhDetailRowChangeEventHandler(object sender, KkhDetailRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class KkhDetailDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnseikyuGenpyoBango;
            
            private global::System.Data.DataColumn columnshubetsu;
            
            private global::System.Data.DataColumn columnkenMei;
            
            private global::System.Data.DataColumn columnhimokuMei;
            
            private global::System.Data.DataColumn columnbangumiMei;
            
            private global::System.Data.DataColumn columnhosoTsuki;
            
            private global::System.Data.DataColumn columnbaitaiMei;
            
            private global::System.Data.DataColumn columnseisakuNaiyo;
            
            private global::System.Data.DataColumn columnkeisaiBi;
            
            private global::System.Data.DataColumn columnhosoKaisu;
            
            private global::System.Data.DataColumn columntanka;
            
            private global::System.Data.DataColumn columnkeisaiGo;
            
            private global::System.Data.DataColumn columnsupesu;
            
            private global::System.Data.DataColumn columnseikyuKinGaku;
            
            private global::System.Data.DataColumn columnshohizeiGaku;
            
            private global::System.Data.DataColumn columnsotoBango;
            
            private global::System.Data.DataColumn columnbusho;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public KkhDetailDataTable() {
                this.TableName = "KkhDetail";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal KkhDetailDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected KkhDetailDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn seikyuGenpyoBangoColumn {
                get {
                    return this.columnseikyuGenpyoBango;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn shubetsuColumn {
                get {
                    return this.columnshubetsu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn kenMeiColumn {
                get {
                    return this.columnkenMei;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn himokuMeiColumn {
                get {
                    return this.columnhimokuMei;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn bangumiMeiColumn {
                get {
                    return this.columnbangumiMei;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn hosoTsukiColumn {
                get {
                    return this.columnhosoTsuki;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn baitaiMeiColumn {
                get {
                    return this.columnbaitaiMei;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn seisakuNaiyoColumn {
                get {
                    return this.columnseisakuNaiyo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn keisaiBiColumn {
                get {
                    return this.columnkeisaiBi;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn hosoKaisuColumn {
                get {
                    return this.columnhosoKaisu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn tankaColumn {
                get {
                    return this.columntanka;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn keisaiGoColumn {
                get {
                    return this.columnkeisaiGo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn supesuColumn {
                get {
                    return this.columnsupesu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn seikyuKinGakuColumn {
                get {
                    return this.columnseikyuKinGaku;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn shohizeiGakuColumn {
                get {
                    return this.columnshohizeiGaku;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sotoBangoColumn {
                get {
                    return this.columnsotoBango;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn bushoColumn {
                get {
                    return this.columnbusho;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public KkhDetailRow this[int index] {
                get {
                    return ((KkhDetailRow)(this.Rows[index]));
                }
            }
            
            public event KkhDetailRowChangeEventHandler KkhDetailRowChanging;
            
            public event KkhDetailRowChangeEventHandler KkhDetailRowChanged;
            
            public event KkhDetailRowChangeEventHandler KkhDetailRowDeleting;
            
            public event KkhDetailRowChangeEventHandler KkhDetailRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddKkhDetailRow(KkhDetailRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public KkhDetailRow AddKkhDetailRow(
                        string seikyuGenpyoBango, 
                        string shubetsu, 
                        string kenMei, 
                        string himokuMei, 
                        string bangumiMei, 
                        string hosoTsuki, 
                        string baitaiMei, 
                        string seisakuNaiyo, 
                        string keisaiBi, 
                        string hosoKaisu, 
                        decimal tanka, 
                        string keisaiGo, 
                        string supesu, 
                        decimal seikyuKinGaku, 
                        decimal shohizeiGaku, 
                        string sotoBango, 
                        string busho) {
                KkhDetailRow rowKkhDetailRow = ((KkhDetailRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        seikyuGenpyoBango,
                        shubetsu,
                        kenMei,
                        himokuMei,
                        bangumiMei,
                        hosoTsuki,
                        baitaiMei,
                        seisakuNaiyo,
                        keisaiBi,
                        hosoKaisu,
                        tanka,
                        keisaiGo,
                        supesu,
                        seikyuKinGaku,
                        shohizeiGaku,
                        sotoBango,
                        busho};
                rowKkhDetailRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowKkhDetailRow);
                return rowKkhDetailRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                KkhDetailDataTable cln = ((KkhDetailDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new KkhDetailDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnseikyuGenpyoBango = base.Columns["seikyuGenpyoBango"];
                this.columnshubetsu = base.Columns["shubetsu"];
                this.columnkenMei = base.Columns["kenMei"];
                this.columnhimokuMei = base.Columns["himokuMei"];
                this.columnbangumiMei = base.Columns["bangumiMei"];
                this.columnhosoTsuki = base.Columns["hosoTsuki"];
                this.columnbaitaiMei = base.Columns["baitaiMei"];
                this.columnseisakuNaiyo = base.Columns["seisakuNaiyo"];
                this.columnkeisaiBi = base.Columns["keisaiBi"];
                this.columnhosoKaisu = base.Columns["hosoKaisu"];
                this.columntanka = base.Columns["tanka"];
                this.columnkeisaiGo = base.Columns["keisaiGo"];
                this.columnsupesu = base.Columns["supesu"];
                this.columnseikyuKinGaku = base.Columns["seikyuKinGaku"];
                this.columnshohizeiGaku = base.Columns["shohizeiGaku"];
                this.columnsotoBango = base.Columns["sotoBango"];
                this.columnbusho = base.Columns["busho"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnseikyuGenpyoBango = new global::System.Data.DataColumn("seikyuGenpyoBango", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnseikyuGenpyoBango);
                this.columnshubetsu = new global::System.Data.DataColumn("shubetsu", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnshubetsu);
                this.columnkenMei = new global::System.Data.DataColumn("kenMei", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnkenMei);
                this.columnhimokuMei = new global::System.Data.DataColumn("himokuMei", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnhimokuMei);
                this.columnbangumiMei = new global::System.Data.DataColumn("bangumiMei", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbangumiMei);
                this.columnhosoTsuki = new global::System.Data.DataColumn("hosoTsuki", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnhosoTsuki);
                this.columnbaitaiMei = new global::System.Data.DataColumn("baitaiMei", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbaitaiMei);
                this.columnseisakuNaiyo = new global::System.Data.DataColumn("seisakuNaiyo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnseisakuNaiyo);
                this.columnkeisaiBi = new global::System.Data.DataColumn("keisaiBi", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnkeisaiBi);
                this.columnhosoKaisu = new global::System.Data.DataColumn("hosoKaisu", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnhosoKaisu);
                this.columntanka = new global::System.Data.DataColumn("tanka", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntanka);
                this.columnkeisaiGo = new global::System.Data.DataColumn("keisaiGo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnkeisaiGo);
                this.columnsupesu = new global::System.Data.DataColumn("supesu", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsupesu);
                this.columnseikyuKinGaku = new global::System.Data.DataColumn("seikyuKinGaku", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnseikyuKinGaku);
                this.columnshohizeiGaku = new global::System.Data.DataColumn("shohizeiGaku", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnshohizeiGaku);
                this.columnsotoBango = new global::System.Data.DataColumn("sotoBango", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsotoBango);
                this.columnbusho = new global::System.Data.DataColumn("busho", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbusho);
                this.columnkenMei.Caption = "Column1";
                this.columnhimokuMei.Caption = "Column1";
                this.columnhosoTsuki.Caption = "Column1";
                this.columnbaitaiMei.Caption = "Column1";
                this.columnseisakuNaiyo.Caption = "Column1";
                this.columnkeisaiBi.Caption = "Column1";
                this.columnhosoKaisu.Caption = "Column1";
                this.columntanka.Caption = "Column1";
                this.columnkeisaiGo.Caption = "Column1";
                this.columnsupesu.Caption = "Column1";
                this.columnseikyuKinGaku.Caption = "Column1";
                this.columnshohizeiGaku.Caption = "Column1";
                this.columnsotoBango.Caption = "Column1";
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public KkhDetailRow NewKkhDetailRow() {
                return ((KkhDetailRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new KkhDetailRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(KkhDetailRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.KkhDetailRowChanged != null)) {
                    this.KkhDetailRowChanged(this, new KkhDetailRowChangeEvent(((KkhDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.KkhDetailRowChanging != null)) {
                    this.KkhDetailRowChanging(this, new KkhDetailRowChangeEvent(((KkhDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.KkhDetailRowDeleted != null)) {
                    this.KkhDetailRowDeleted(this, new KkhDetailRowChangeEvent(((KkhDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.KkhDetailRowDeleting != null)) {
                    this.KkhDetailRowDeleting(this, new KkhDetailRowChangeEvent(((KkhDetailRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveKkhDetailRow(KkhDetailRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DetailDSUni ds = new DetailDSUni();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "KkhDetailDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class KkhDetailRow : global::System.Data.DataRow {
            
            private KkhDetailDataTable tableKkhDetail;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal KkhDetailRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableKkhDetail = ((KkhDetailDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string seikyuGenpyoBango {
                get {
                    try {
                        return ((string)(this[this.tableKkhDetail.seikyuGenpyoBangoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'seikyuGenpyoBango\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.seikyuGenpyoBangoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string shubetsu {
                get {
                    try {
                        return ((string)(this[this.tableKkhDetail.shubetsuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'shubetsu\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.shubetsuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string kenMei {
                get {
                    try {
                        return ((string)(this[this.tableKkhDetail.kenMeiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'kenMei\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.kenMeiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string himokuMei {
                get {
                    try {
                        return ((string)(this[this.tableKkhDetail.himokuMeiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'himokuMei\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.himokuMeiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string bangumiMei {
                get {
                    try {
                        return ((string)(this[this.tableKkhDetail.bangumiMeiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'bangumiMei\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.bangumiMeiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string hosoTsuki {
                get {
                    try {
                        return ((string)(this[this.tableKkhDetail.hosoTsukiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'hosoTsuki\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.hosoTsukiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string baitaiMei {
                get {
                    try {
                        return ((string)(this[this.tableKkhDetail.baitaiMeiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'baitaiMei\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.baitaiMeiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string seisakuNaiyo {
                get {
                    try {
                        return ((string)(this[this.tableKkhDetail.seisakuNaiyoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'seisakuNaiyo\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.seisakuNaiyoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string keisaiBi {
                get {
                    try {
                        return ((string)(this[this.tableKkhDetail.keisaiBiColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'keisaiBi\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.keisaiBiColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string hosoKaisu {
                get {
                    try {
                        return ((string)(this[this.tableKkhDetail.hosoKaisuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'hosoKaisu\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.hosoKaisuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal tanka {
                get {
                    try {
                        return ((decimal)(this[this.tableKkhDetail.tankaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'tanka\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.tankaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string keisaiGo {
                get {
                    try {
                        return ((string)(this[this.tableKkhDetail.keisaiGoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'keisaiGo\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.keisaiGoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string supesu {
                get {
                    try {
                        return ((string)(this[this.tableKkhDetail.supesuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'supesu\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.supesuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal seikyuKinGaku {
                get {
                    try {
                        return ((decimal)(this[this.tableKkhDetail.seikyuKinGakuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'seikyuKinGaku\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.seikyuKinGakuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal shohizeiGaku {
                get {
                    try {
                        return ((decimal)(this[this.tableKkhDetail.shohizeiGakuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'shohizeiGaku\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.shohizeiGakuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string sotoBango {
                get {
                    try {
                        return ((string)(this[this.tableKkhDetail.sotoBangoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'sotoBango\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.sotoBangoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string busho {
                get {
                    try {
                        return ((string)(this[this.tableKkhDetail.bushoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'KkhDetail\' にある列 \'busho\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableKkhDetail.bushoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsseikyuGenpyoBangoNull() {
                return this.IsNull(this.tableKkhDetail.seikyuGenpyoBangoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetseikyuGenpyoBangoNull() {
                this[this.tableKkhDetail.seikyuGenpyoBangoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsshubetsuNull() {
                return this.IsNull(this.tableKkhDetail.shubetsuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetshubetsuNull() {
                this[this.tableKkhDetail.shubetsuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IskenMeiNull() {
                return this.IsNull(this.tableKkhDetail.kenMeiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetkenMeiNull() {
                this[this.tableKkhDetail.kenMeiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IshimokuMeiNull() {
                return this.IsNull(this.tableKkhDetail.himokuMeiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SethimokuMeiNull() {
                this[this.tableKkhDetail.himokuMeiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsbangumiMeiNull() {
                return this.IsNull(this.tableKkhDetail.bangumiMeiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetbangumiMeiNull() {
                this[this.tableKkhDetail.bangumiMeiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IshosoTsukiNull() {
                return this.IsNull(this.tableKkhDetail.hosoTsukiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SethosoTsukiNull() {
                this[this.tableKkhDetail.hosoTsukiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsbaitaiMeiNull() {
                return this.IsNull(this.tableKkhDetail.baitaiMeiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetbaitaiMeiNull() {
                this[this.tableKkhDetail.baitaiMeiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsseisakuNaiyoNull() {
                return this.IsNull(this.tableKkhDetail.seisakuNaiyoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetseisakuNaiyoNull() {
                this[this.tableKkhDetail.seisakuNaiyoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IskeisaiBiNull() {
                return this.IsNull(this.tableKkhDetail.keisaiBiColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetkeisaiBiNull() {
                this[this.tableKkhDetail.keisaiBiColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IshosoKaisuNull() {
                return this.IsNull(this.tableKkhDetail.hosoKaisuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SethosoKaisuNull() {
                this[this.tableKkhDetail.hosoKaisuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IstankaNull() {
                return this.IsNull(this.tableKkhDetail.tankaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SettankaNull() {
                this[this.tableKkhDetail.tankaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IskeisaiGoNull() {
                return this.IsNull(this.tableKkhDetail.keisaiGoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetkeisaiGoNull() {
                this[this.tableKkhDetail.keisaiGoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IssupesuNull() {
                return this.IsNull(this.tableKkhDetail.supesuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetsupesuNull() {
                this[this.tableKkhDetail.supesuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsseikyuKinGakuNull() {
                return this.IsNull(this.tableKkhDetail.seikyuKinGakuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetseikyuKinGakuNull() {
                this[this.tableKkhDetail.seikyuKinGakuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsshohizeiGakuNull() {
                return this.IsNull(this.tableKkhDetail.shohizeiGakuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetshohizeiGakuNull() {
                this[this.tableKkhDetail.shohizeiGakuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IssotoBangoNull() {
                return this.IsNull(this.tableKkhDetail.sotoBangoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetsotoBangoNull() {
                this[this.tableKkhDetail.sotoBangoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsbushoNull() {
                return this.IsNull(this.tableKkhDetail.bushoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetbushoNull() {
                this[this.tableKkhDetail.bushoColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class KkhDetailRowChangeEvent : global::System.EventArgs {
            
            private KkhDetailRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public KkhDetailRowChangeEvent(KkhDetailRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public KkhDetailRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591