//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.5485
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isid.KKH.Lion.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Isid.KKH.Lion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Lion_Baitai_Mcr {
            get {
                object obj = ResourceManager.GetObject("Lion_Baitai_Mcr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lion_Baitai_Template {
            get {
                object obj = ResourceManager.GetObject("Lion_Baitai_Template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lion_Baitai_Template2 {
            get {
                object obj = ResourceManager.GetObject("Lion_Baitai_Template2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lion_Mcr {
            get {
                object obj = ResourceManager.GetObject("Lion_Mcr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lion_NewReport_Template {
            get {
                object obj = ResourceManager.GetObject("Lion_NewReport_Template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lion_OrderDiff_Mcr {
            get {
                object obj = ResourceManager.GetObject("Lion_OrderDiff_Mcr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lion_OrderDiff_Template {
            get {
                object obj = ResourceManager.GetObject("Lion_OrderDiff_Template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lion_Seisaku_Mcr {
            get {
                object obj = ResourceManager.GetObject("Lion_Seisaku_Mcr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lion_Seisaku_Template {
            get {
                object obj = ResourceManager.GetObject("Lion_Seisaku_Template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lion_Template {
            get {
                object obj = ResourceManager.GetObject("Lion_Template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LionNewReport {
            get {
                object obj = ResourceManager.GetObject("LionNewReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
