//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3643
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isid.KKH.UserManual.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Isid.KKH.UserManual.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] KKH_Help_Acom {
            get {
                object obj = ResourceManager.GetObject("KKH_Help_Acom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KKH_Help_Ash {
            get {
                object obj = ResourceManager.GetObject("KKH_Help_Ash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KKH_Help_AshBear {
            get {
                object obj = ResourceManager.GetObject("KKH_Help_AshBear", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KKH_Help_Epson {
            get {
                object obj = ResourceManager.GetObject("KKH_Help_Epson", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KKH_Help_Kmn {
            get {
                object obj = ResourceManager.GetObject("KKH_Help_Kmn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KKH_Help_Lion4 {
            get {
                object obj = ResourceManager.GetObject("KKH_Help_Lion4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KKH_Help_Mac {
            get {
                object obj = ResourceManager.GetObject("KKH_Help_Mac", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KKH_Help_Rireki {
            get {
                object obj = ResourceManager.GetObject("KKH_Help_Rireki", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KKH_Help_Sample3 {
            get {
                object obj = ResourceManager.GetObject("KKH_Help_Sample3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KKH_Help_Skyp {
            get {
                object obj = ResourceManager.GetObject("KKH_Help_Skyp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KKH_Help_Tkd {
            get {
                object obj = ResourceManager.GetObject("KKH_Help_Tkd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KKH_Help_Toh {
            get {
                object obj = ResourceManager.GetObject("KKH_Help_Toh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KKH_Help_Uni {
            get {
                object obj = ResourceManager.GetObject("KKH_Help_Uni", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
